Repository feather-core/feather-core, pull requests merged in 2019-04, with the labels that each got.

#6 Refactor eventbus API
  eventbus/pom.xml
  eventbus/src/main/java/org/feathercore/eventbus/CancellableEvent.java
  eventbus/src/main/java/org/feathercore/eventbus/Event.java
  eventbus/src/main/java/org/feathercore/eventbus/EventHandler.java
  eventbus/src/main/java/org/feathercore/eventbus/EventManager.java
  eventbus/src/main/java/org/feathercore/eventbus/SimpleCancellableEvent.java
  eventbus/src/main/java/org/feathercore/eventbus/SimpleEventManager.java
  protocol/src/main/java/org/feathercore/protocol/event/PacketReceiveEventSimple.java
  protocol/src/main/java/org/feathercore/protocol/event/PreConnectionEvent.java
  protocol/src/main/java/org/feathercore/protocol/event/PreConnectionEventSimple.java
  protocol/src/main/java/org/feathercore/protocol/event/PreDisconnectionEvent.java
  protocol/src/main/java/org/feathercore/protocol/netty/HandlerBoss.java
Labels: enhancement

#9 Implement basic but needed elements of protocol
  pom.xml
  protocol/src/main/java/org/feathercore/protocol/Buffer.java
  protocol/src/main/java/org/feathercore/protocol/Connection.java
  protocol/src/main/java/org/feathercore/protocol/encrypt/CryptManager.java
  protocol/src/main/java/org/feathercore/protocol/encrypt/EncryptionRequestContext.java
  protocol/src/main/java/org/feathercore/protocol/event/PacketReceiveEvent.java
  protocol/src/main/java/org/feathercore/protocol/event/PreConnectionEvent.java
  protocol/src/main/java/org/feathercore/protocol/minecraft/packet/login/client/LoginPacketClientEncryptionResponse.java
  protocol/src/main/java/org/feathercore/protocol/minecraft/packet/login/server/LoginPacketServerEncryptionRequest.java
  protocol/src/main/java/org/feathercore/protocol/netty/HandlerBoss.java
  protocol/src/main/java/org/feathercore/protocol/netty/NettyBuffer.java
  protocol/src/main/java/org/feathercore/protocol/netty/NettyConnection.java
  protocol/src/main/java/org/feathercore/protocol/netty/codec/Decompressor.java
  protocol/src/main/java/org/feathercore/protocol/netty/util/NettyAttributes.java
  protocol/src/main/java/org/feathercore/protocol/netty/util/SharedNettyResources.java
  protocol/src/main/java/org/feathercore/protocol/packet/Packet.java
  protocol/src/main/java/org/feathercore/protocol/packet/PacketType.java
  protocol/src/main/java/org/feathercore/protocol/registry/AbstractPacketRegistry.java
  protocol/src/main/java/org/feathercore/protocol/registry/ArrayBasedPacketRegistry.java
  protocol/src/main/java/org/feathercore/protocol/registry/PacketRegistry.java
  protocol/src/main/java/org/feathercore/protocol/registry/common/CommonHandshakePacketRegistry.java
  protocol/src/main/java/org/feathercore/protocol/registry/common/CommonLoginPacketRegistry.java
Labels: enhancement

#19 Add sounds and particles
  shared/src/main/java/org/feathercore/shared/particle/MinecraftParticle.java
  shared/src/main/java/org/feathercore/shared/particle/Particle.java
  shared/src/main/java/org/feathercore/shared/sound/MinecraftSound.java
  shared/src/main/java/org/feathercore/shared/sound/Sound.java
Labels: enhancement

#21 Nbt
  shared/src/main/java/org/feathercore/shared/nbt/tag/exact/ByteTag.java
  shared/src/main/java/org/feathercore/shared/nbt/tag/exact/CompoundTag.java
  shared/src/main/java/org/feathercore/shared/nbt/tag/exact/DoubleTag.java
  shared/src/main/java/org/feathercore/shared/nbt/tag/exact/FloatTag.java
  shared/src/main/java/org/feathercore/shared/nbt/tag/exact/IntTag.java
  shared/src/main/java/org/feathercore/shared/nbt/tag/exact/ListTag.java
  shared/src/main/java/org/feathercore/shared/nbt/tag/exact/LongTag.java
  shared/src/main/java/org/feathercore/shared/nbt/tag/exact/ShortTag.java
Labels: enhancement

#22 Modules API
  module-api/pom.xml
  module-api/src/main/java/ru/feathercore/moduleapi/AbstractModuleLoader.java
  module-api/src/main/java/ru/feathercore/moduleapi/Module.java
  module-api/src/main/java/ru/feathercore/moduleapi/ModuleConfigurationException.java
  module-api/src/main/java/ru/feathercore/moduleapi/ModuleInitializationException.java
  module-api/src/main/java/ru/feathercore/moduleapi/ModuleInitializer.java
  module-api/src/main/java/ru/feathercore/moduleapi/ModuleLoader.java
  module-api/src/main/java/ru/feathercore/moduleapi/package-info.java
  pom.xml
  shared/src/main/java/org/feathercore/shared/object/ValueContainer.java
Labels: enhancement

#25 Create README.md
  README.md
Labels: repository management

#26 Upstream: minecraft-packets <- development
  README.md
  module-api/pom.xml
  module-api/src/main/java/ru/feathercore/moduleapi/AbstractModuleLoader.java
  module-api/src/main/java/ru/feathercore/moduleapi/Module.java
  module-api/src/main/java/ru/feathercore/moduleapi/ModuleConfigurationException.java
  module-api/src/main/java/ru/feathercore/moduleapi/ModuleInitializationException.java
  module-api/src/main/java/ru/feathercore/moduleapi/ModuleInitializer.java
  module-api/src/main/java/ru/feathercore/moduleapi/ModuleLoader.java
  module-api/src/main/java/ru/feathercore/moduleapi/package-info.java
  pom.xml
  shared/src/main/java/org/feathercore/shared/object/ValueContainer.java
Labels: upstream
